### ISSUE TITLE
pkg_resources missing

### ISSUE THREAD

**Issue by hobakill** [deanishe/alfred-convert#57]
cannot run the `conv` workflow at all. seemingly missing a dependency

```
[08:49:00.433] Logging Started...
[08:49:07.562] Convert[Script Filter] Queuing argument '100 '
[08:49:07.671] Convert[Script Filter] Script with argv '100 ' finished
[08:49:07.675] ERROR: Convert[Script Filter] Code 1: Traceback (most recent call last):
  File "convert.py", line 18, in <module>
    from pint import UnitRegistry, UndefinedUnitError, DimensionalityError
  File "/Users/me/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.F3887D31-AD9B-4A50-B50A-80C3D521066B/pint/__init__.py", line 17, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
```

**Comment by deanishe** [comment]
> seemingly missing a dependency

Yes. It's an upstream problem with `pint` that was never actually fixed: hgrecco/pint#28.

Run `easy_install --user setuptools` in Terminal. That should fix the problem.

I'll submit a bug report to `pint`.

**Comment by deanishe** [comment]
Pint bug report: hgrecco/pint#872

**Comment by hobakill** [comment]
`v3.6.2` did the trick. thanks for doing the python heavy lifting! :)
