### ISSUE TITLE
while opening none, inline none: missing unary operator

### ISSUE THREAD

**Issue by ramay29** [deanishe/alfred-convert#89]
Here is the debug. I have cleared cache as well but still same error. 

[12:21:37.344] Convert[Script Filter] Queuing argument '1'
[12:21:38.277] Convert[Script Filter] Script with argv '1' finished
[12:21:38.283] ERROR: Convert[Script Filter] Code 1: .
http_proxy=
https_proxy=
.
12:21:37 workflow.py:2061 DEBUG    ---------- Convert (3.7.1) ----------
12:21:37 workflow.py:1468 DEBUG    reading settings from /Users/Ramay/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred-convert/settings.json
12:21:37 workflow.py:2343 DEBUG    update check not due
12:21:38 convert.py:646 DEBUG    query : 1
12:21:38 workflow.py:2225 DEBUG    last run version: 3.7.1
12:21:38 convert.py:103 DEBUG    version=3.7.1, last_version=3.7.1
12:21:38 workflow.py:1695 DEBUG    loading cached data: /Users/Ramay/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-convert/__workflow_latest_version.cpickle
12:21:38 workflow.py:1695 DEBUG    loading cached data: /Users/Ramay/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred-convert/exchange_rates.cpickle
12:21:38 convert.py:547 DEBUG    registering currency : 'DZD = usd / 138.725751 = dzd'
12:21:38 convert.py:547 DEBUG    registering currency : 'NAD = usd / 15.52 = nad'
12:21:38 convert.py:547 DEBUG    registering currency : 'GHS = usd / 6.136865 = ghs'
12:21:38 convert.py:547 DEBUG    registering currency : 'EGP = usd / 15.7387 = egp'
12:21:38 convert.py:547 DEBUG    registering currency : 'BGN = usd / 1.731695 = bgn'
12:21:38 convert.py:547 DEBUG    registering currency : 'PAB = usd / 1 = pab'
12:21:38 convert.py:547 DEBUG    registering currency : 'BOB = usd / 6.895739 = bob'
12:21:38 convert.py:547 DEBUG    registering currency : 'DKK = usd / 6.579994 = dkk'
12:21:38 convert.py:547 DEBUG    registering currency : 'BWP = usd / 11.455946 = bwp'
12:21:38 convert.py:547 DEBUG    registering currency : 'LBP = usd / 1529.812979 = lbp'
12:21:38 convert.py:547 DEBUG    registering currency : 'TZS = usd / 2301 = tzs'
12:21:38 convert.py:547 DEBUG    registering currency : 'VND = usd / 22779.31862 = vnd'
12:21:38 convert.py:547 DEBUG    registering currency : 'AOA = usd / 596.901 = aoa'
12:21:38 convert.py:547 DEBUG    registering currency : 'KHR = usd / 4069.052226'
12:21:38 convert.py:547 DEBUG    registering currency : 'QAR = usd / 3.641 = qar'
12:21:38 convert.py:547 DEBUG    registering currency : 'KYD = usd / 0.83344'
12:21:38 convert.py:547 DEBUG    registering currency : 'LYD = usd / 4.583815 = lyd'
12:21:38 convert.py:547 DEBUG    registering currency : 'UAH = usd / 26.431114 = uah'
12:21:38 convert.py:547 DEBUG    registering currency : 'JOD = usd / 0.7092 = jod'
12:21:38 convert.py:547 DEBUG    registering currency : 'AWG = usd / 1.80025 = awg'
12:21:38 convert.py:547 DEBUG    registering currency : 'SAR = usd / 3.752379 = sar'
12:21:38 convert.py:547 DEBUG    registering currency : 'BND = usd / 1.353933 = bnd'
12:21:38 convert.py:547 DEBUG    registering currency : 'HKD = usd / 7.788141 = hkd'
12:21:38 convert.py:547 DEBUG    registering currency : 'CHF = usd / 0.931311 = chf'
12:21:38 convert.py:547 DEBUG    registering currency : 'GIP = usd / 0.744025 = gip'
12:21:38 convert.py:547 DEBUG    registering currency : 'XPF = usd / 105.582196 = xpf'
12:21:38 convert.py:547 DEBUG    registering currency : 'XPD = usd / 0.00046191 = xpd'
12:21:38 convert.py:547 DEBUG    registering currency : 'BYN = usd / 2.468206 = byn'
12:21:38 convert.py:547 DEBUG    registering currency : 'MRO = usd / 356.999828 = mro'
12:21:38 convert.py:547 DEBUG    registering currency : 'HRK = usd / 6.6441 = hrk'
12:21:38 convert.py:547 DEBUG    registering currency : 'DJF = usd / 178.038228 = djf'
12:21:38 convert.py:547 DEBUG    registering currency : 'THB = usd / 32.742 = thb'
12:21:38 convert.py:547 DEBUG    registering currency : 'XAF = usd / 580.376848 = xaf'
12:21:38 convert.py:547 DEBUG    registering currency : 'XAG = usd / 0.04001043 = xag'
12:21:38 convert.py:547 DEBUG    registering currency : 'ETB = usd / 47.32 = etb'
12:21:38 convert.py:547 DEBUG    registering currency : 'UYU = usd / 44.136437 = uyu'
12:21:38 convert.py:547 DEBUG    registering currency : 'NIO = usd / 35.229582 = nio'
12:21:38 convert.py:547 DEBUG    registering currency : 'LAK = usd / 10666.133442 = lak'
12:21:38 convert.py:547 DEBUG    registering currency : 'SYP = usd / 1256.831186 = syp'
12:21:38 convert.py:547 DEBUG    registering currency : 'MAD = usd / 9.179175 = mad'
12:21:38 convert.py:547 DEBUG    registering currency : 'MZN = usd / 63.842 = mzn'
12:21:38 convert.py:547 DEBUG    registering currency : 'YER = usd / 250.249937 = yer'
12:21:38 convert.py:547 DEBUG    registering currency : 'ZAR = usd / 15.50383 = zar'
12:21:38 convert.py:547 DEBUG    registering currency : 'NPR = usd / 119.028869 = npr'
12:21:38 convert.py:547 DEBUG    registering currency : 'NGN = usd / 410.68 = ngn'
12:21:38 convert.py:547 DEBUG    registering currency : 'CRC = usd / 642.618901 = crc'
12:21:38 convert.py:547 DEBUG    registering currency : 'AED = usd / 3.672937 = aed'
12:21:38 convert.py:547 DEBUG    registering currency : 'GBP = usd / 0.744025 = gbp'
12:21:38 convert.py:547 DEBUG    registering currency : 'MWK = usd / 816.144854 = mwk'
12:21:38 convert.py:547 DEBUG    registering currency : 'LKR = usd / 202.020443 = lkr'
12:21:38 convert.py:547 DEBUG    registering currency : 'PKR = usd / 174.55 = pkr'
12:21:38 convert.py:547 DEBUG    registering currency : 'HUF = usd / 322.914574 = huf'
12:21:38 convert.py:547 DEBUG    registering currency : 'BMD = usd / 1 = bmd'
12:21:38 convert.py:547 DEBUG    registering currency : 'LSL = usd / 15.419549 = lsl'
12:21:38 convert.py:547 DEBUG    registering currency : 'MNT = usd / 2859.434306 = mnt'
12:21:38 convert.py:547 DEBUG    registering currency : 'AMD = usd / 475.745601 = amd'
12:21:38 convert.py:547 DEBUG    registering currency : 'UGX = usd / 3535.245273 = ugx'
12:21:38 convert.py:547 DEBUG    registering currency : 'XDR = usd / 0.71202 = xdr'
12:21:38 convert.py:547 DEBUG    registering currency : 'JMD = usd / 155.311125 = jmd'
12:21:38 convert.py:547 DEBUG    registering currency : 'TTD = usd / 6.79069 = ttd'
12:21:38 convert.py:547 DEBUG    registering currency : 'SHP = usd / 0.744025 = shp'
12:21:38 convert.py:547 DEBUG    registering currency : 'AFN = usd / 93.900446 = afn'
12:21:38 convert.py:547 DEBUG    registering currency : 'MMK = usd / 1769.681936 = mmk'
12:21:38 convert.py:547 DEBUG    registering currency : 'HasWarning = usd / False = haswarning'
12:21:38 convert.py:547 DEBUG    registering currency : 'KPW = usd / 900 = kpw'
12:21:38 convert.py:547 DEBUG    registering currency : 'TRY = usd / 10.413502 = try'
12:21:38 convert.py:547 DEBUG    registering currency : 'BDT = usd / 85.803732 = bdt'
12:21:38 convert.py:547 DEBUG    registering currency : 'CNY = usd / 6.3859 = cny'
12:21:38 convert.py:547 DEBUG    registering currency : 'HTG = usd / 99.080193 = htg'
12:21:38 convert.py:547 DEBUG    registering currency : 'SLL = usd / 10952.049921 = sll'
12:21:38 convert.py:547 DEBUG    registering currency : 'MGA = usd / 3985.681319 = mga'
12:21:38 convert.py:547 DEBUG    registering currency : 'PHP = usd / 50.36925'
12:21:38 convert.py:547 DEBUG    registering currency : 'LRD = usd / 143.549989 = lrd'
12:21:38 convert.py:547 DEBUG    registering currency : 'XCD = usd / 2.70255 = xcd'
12:21:38 convert.py:547 DEBUG    registering currency : 'NOK = usd / 8.754395 = nok'
12:21:38 convert.py:547 DEBUG    registering currency : 'MOP = usd / 8.023121 = mop'
12:21:38 convert.py:547 DEBUG    registering currency : 'SSP = usd / 130.26 = ssp'
12:21:38 convert.py:547 DEBUG    registering currency : 'INR = usd / 74.383837 = inr'
12:21:38 convert.py:547 DEBUG    registering currency : 'MXN = usd / 20.740959 = mxn'
12:21:38 convert.py:547 DEBUG    registering currency : 'CZK = usd / 22.338291 = czk'
12:21:38 convert.py:547 DEBUG    registering currency : 'TJS = usd / 11.296173 = tjs'
12:21:38 convert.py:547 DEBUG    registering currency : 'BTC = usd / 1.6788508e-05 = btc'
12:21:38 convert.py:547 DEBUG    registering currency : 'Message = usd / You are over your rate limit please upgrade your account! = message'
12:21:38 convert.py:547 DEBUG    registering currency : 'BTN = usd / 74.39283 = btn'
12:21:38 convert.py:547 DEBUG    registering currency : 'COP = usd / 3906.978595 = cop'
12:21:38 convert.py:547 DEBUG    registering currency : 'MYR = usd / 4.176 = myr'
12:21:38 convert.py:547 DEBUG    registering currency : 'TMT = usd / 3.5 = tmt'
12:21:38 convert.py:547 DEBUG    registering currency : 'MUR = usd / 43.35 = mur'
12:21:38 convert.py:547 DEBUG    registering currency : 'IDR = usd / 14256.85 = idr'
12:21:38 convert.py:547 DEBUG    registering currency : 'GEL = usd / 3.14 = gel'
12:21:38 convert.py:547 DEBUG    registering currency : 'FJD = usd / 2.10225 = fjd'
12:21:38 convert.py:547 DEBUG    registering currency : 'ISK = usd / 133.07 = isk'
12:21:38 convert.py:547 DEBUG    registering currency : 'PEN = usd / 3.996962 = pen'
12:21:38 convert.py:547 DEBUG    registering currency : 'BZD = usd / 2.015845 = bzd'
12:21:38 convert.py:547 DEBUG    registering currency : 'ILS = usd / 3.096852 = ils'
12:21:38 convert.py:547 DEBUG    registering currency : 'DOP = usd / 56.538305 = dop'
12:21:38 convert.py:547 DEBUG    registering currency : 'GGP = usd / 0.744025 = ggp'
12:21:38 convert.py:547 DEBUG    registering currency : 'MDL = usd / 17.649228 = mdl'
12:21:38 convert.py:547 DEBUG    registering currency : 'XPT = usd / 0.00093415 = xpt'
12:21:38 convert.py:547 DEBUG    registering currency : 'BSD = usd / 1 = bsd'
12:21:38 convert.py:547 DEBUG    registering currency : 'SEK = usd / 8.900549 = sek'
12:21:38 convert.py:547 DEBUG    registering currency : 'Response = usd / Error = response'
12:21:38 convert.py:547 DEBUG    registering currency : 'JEP = usd / 0.744025 = jep'
12:21:38 convert.py:547 DEBUG    registering currency : 'AUD = usd / 1.370859 = aud'
12:21:38 convert.py:547 DEBUG    registering currency : 'SRD = usd / 21.513 = srd'
12:21:38 convert.py:547 DEBUG    registering currency : 'CUP = usd / 25.75'
12:21:38 convert.py:547 DEBUG    registering currency : 'CLF = usd / 0.029428 = clf'
12:21:38 convert.py:547 DEBUG    registering currency : 'BBD = usd / 2 = bbd'
12:21:38 convert.py:547 DEBUG    registering currency : 'KMF = usd / 434.599845 = kmf'
12:21:38 convert.py:547 DEBUG    registering currency : 'KRW = usd / 1182.250274 = krw'
12:21:38 convert.py:547 DEBUG    registering currency : 'GMD = usd / 52.35 = gmd'
12:21:38 convert.py:547 DEBUG    registering currency : 'IMP = usd / 0.744025 = imp'
12:21:38 convert.py:547 DEBUG    registering currency : 'ANG = usd / 1.80241 = ang'
12:21:38 convert.py:547 DEBUG    registering currency : 'CUC = usd / 1 = cuc'
12:21:38 convert.py:547 DEBUG    registering currency : 'CLP = usd / 812 = clp'
12:21:38 convert.py:547 DEBUG    registering currency : 'ZMW = usd / 17.546288 = zmw'
12:21:38 convert.py:547 DEBUG    registering currency : 'EUR = usd / 0.884779 = eur'
12:21:38 convert.py:547 DEBUG    registering currency : 'ALL = usd / 107.288517 = all'
12:21:38 convert.py:547 DEBUG    registering currency : 'RWF = usd / 1013.928591 = rwf'
12:21:38 convert.py:547 DEBUG    registering currency : 'KZT = usd / 432.045999 = kzt'
12:21:38 convert.py:547 DEBUG    registering currency : 'RUB = usd / 73.019313 = rub'
12:21:38 convert.py:547 DEBUG    registering currency : 'Data = usd / {} = data'
12:21:38 workflow.py:2080 ERROR    While opening None, in line None: missing unary operator "/"
Traceback (most recent call last):
  File "/Users/Ramay/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D075CBF6-35CA-4977-875D-FBE8161CA1EB/workflow/workflow.py", line 2073, in run
    func(self)
  File "convert.py", line 666, in main
    register_exchange_rates(exchange_rates)
  File "convert.py", line 548, in register_exchange_rates
    ureg.define(definition)
  File "/Users/Ramay/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D075CBF6-35CA-4977-875D-FBE8161CA1EB/pint/registry.py", line 233, in define
    self._define(Definition.from_string(line))
  File "/Users/Ramay/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D075CBF6-35CA-4977-875D-FBE8161CA1EB/pint/definitions.py", line 57, in from_string
    return UnitDefinition(name, symbol, aliases, value)
  File "/Users/Ramay/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D075CBF6-35CA-4977-875D-FBE8161CA1EB/pint/definitions.py", line 117, in __init__
    converter = ParserHelper.from_string(converter)
  File "/Users/Ramay/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D075CBF6-35CA-4977-875D-FBE8161CA1EB/pint/util.py", line 423, in from_string
    return cls._from_string(input_string)
  File "/Users/Ramay/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D075CBF6-35CA-4977-875D-FBE8161CA1EB/pint/compat/lrucache.py", line 129, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/Ramay/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D075CBF6-35CA-4977-875D-FBE8161CA1EB/pint/util.py", line 458, in _from_string
    ret = build_eval_tree(gen).evaluate(cls.eval_token)
  File "/Users/Ramay/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D075CBF6-35CA-4977-875D-FBE8161CA1EB/pint/pint_eval.py", line 90, in evaluate
    raise DefinitionSyntaxError('missing unary operator "%s"' % op_text)
DefinitionSyntaxError: While opening None, in line None: missing unary operator "/"
12:21:38 workflow.py:2082 INFO     for assistance, see: https://github.com/deanishe/alfred-convert/issues
12:21:38 workflow.py:2103 DEBUG    ---------- finished in 0.427s ----------
[12:21:38.293] Convert[Script Filter] {
  "items": [
    {
      "valid": false,
      "subtitle": "While opening None, in line None: missing unary operator \"/\"",
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      },
      "title": "Error in workflow 'Convert'"
    }
  ]
}

**Comment by maindoor** [comment]
I too am getting the same error on Alfred 4.  Any workarounds would also be appreciated.

**Comment by martisj** [comment]
Duplicate of https://github.com/deanishe/alfred-convert/issues/74

running `conv workflow:delcache` (... and waiting for the response) worked for me.

**Comment by nc7s** [comment]
> running `conv workflow:delcache` (... and waiting for the response) worked for me.

Worked for me too.
